spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: apache-kafka:9092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
#      default-binder: apache-kafkaversion